Fix -Werror=maybe-uninitialized on GCC 12
The following error is happening on Ubuntu Lunar (development
version):

In function ‘ip_islocalhost’,
    inlined from ‘gvm_routethrough’ at ./base/networking.c:1032:11:
./base/networking.c:863:22: error: ‘addr6.__in6_u.__u6_addr32[3]’ may be used uninitialized [-Werror=maybe-uninitialized]
./base/networking.c: In function ‘gvm_routethrough’:
./base/networking.c:790:19: note: ‘addr6.__in6_u.__u6_addr32[3]’ was declared here

This commit fixes it by always initializing "addr6" with
"IN6ADDR_ANY_INIT".

Signed-off-by: Sergio Durigan Junior <sergiodj@sergiodj.net>
(cherry picked from commit dd95e594f3644a87d3048e86162dbf7207c71f83)